version: '3.8'

services:
  backend:
    build:
      context: ../../
      dockerfile: backend/Dockerfile
    container_name: deuquantas-backend
    restart: always
    ports:
      - "3001:3001"
      - "3002:3002"
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "deuquantas"
      DATABASE_URL: "postgresql://postgres:password@db:5432/deuquantas"
      JWT_SECRET: "chave-super-secreta"
      NODE_ENV: "development"
      PORT: "3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db
    networks:
      - deuquantas

  frontend:
    build:
      context: ../../
      dockerfile: frontend-web/Dockerfile
      target: development
    container_name: deuquantas-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
      NEXT_PUBLIC_SOCKET_URL: "http://localhost:3002"
      NODE_ENV: "development"
    volumes:
      - ../../frontend-web:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - deuquantas

  db:
    image: postgres:17-alpine
    container_name: deuquantas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deuquantas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - deuquantas

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_URI: "postgresql://postgres:password@db:5432/deuquantas?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "password"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - deuquantas

  adminer:
    image: adminer
    container_name: deuquantas-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - deuquantas

networks:
  deuquantas:
    driver: bridge

volumes:
  postgres_data:
