services:
  backend:
    build:
      context: ../../
      dockerfile: backend/Dockerfile
    container_name: deuquantas-backend
    restart: always
    ports:
      - "3010:3010"
      - "3011:3011"
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "deuquantas"
      DATABASE_URL: "postgresql://postgres:password@db:5432/deuquantas"
      JWT_SECRET: "chave-super-secreta"
      NODE_ENV: "development"
      PORT: "3010"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - deuquantas

  # frontend:
  #   build:
  #     context: ../../
  #     dockerfile: frontend-web-client/Dockerfile
  #     target: development
  #   container_name: deuquantas-frontend-client
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NEXT_PUBLIC_API_URL: "http://localhost:3010"
  #     NEXT_PUBLIC_SOCKET_URL: "http://localhost:3011"
  #     NODE_ENV: "development"
  #   volumes:
  #     - ../../frontend-web-client:/app
  #     - /app/node_modules
  #     - /app/.next
  #   depends_on:
  #     - backend
  #   networks:
  #     - deuquantas

  # frontend-establishment:
  #   build:
  #     context: ../../
  #     dockerfile: frontend-web-establishment/Dockerfile
  #     target: development
  #   container_name: deuquantas-frontend-establishment
  #   restart: always
  #   ports:
  #     - "3001:3001"
  #   environment:
  #     NEXT_PUBLIC_API_URL: "http://localhost:3010"
  #     NEXT_PUBLIC_SOCKET_URL: "http://localhost:3011"
  #     NODE_ENV: "development"
  #   volumes:
  #     - ../../frontend-web-establishment:/app
  #     - /app/node_modules
  #     - /app/.next
  #   depends_on:
  #     - backend
  #   networks:
  #     - deuquantas
          
  db:
    image: postgres:17-alpine
    container_name: deuquantas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deuquantas
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - deuquantas
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_URI: "postgresql://postgres:password@db:5432/deuquantas?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "password"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - deuquantas

  adminer:
    image: adminer
    container_name: deuquantas-adminer
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - deuquantas

networks:
  deuquantas:
    driver: bridge

volumes:
  postgres_data:
