services:
  backend:
    build:
      context: ../../backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/deuquantas"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deuquantas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
