services:
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/backend/Dockerfile
    container_name: deuquantas-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USER: "postgres"
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "deuquantas"
      DATABASE_URL: "postgresql://postgres:password@db:5432/deuquantas"
      JWT_SECRET: "chave-super-secreta"
      NODE_ENV: "development"
    depends_on:
      - db
    networks:
      - deuquantas

  db:
    image: postgis/postgis:13-3.1-alpine
    container_name: deuquantas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deuquantas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - deuquantas

  frontend-web:
    build:
      context: ../../
      dockerfile: infra/docker/frontend/web/Dockerfile.dev
    container_name: deuquantas-frontend-web
    restart: always
    ports:
      - "3004:3000"
    depends_on:
      - backend
    environment:
      PORT: 3000
      NEXT_PUBLIC_DOCKER_ENV: true
      REACT_APP_BACKEND_URL: "http://backend:3000"
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../../frontend-web:/app
      - /app/node_modules
      - /app/.next
    networks:
      - deuquantas

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ../monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../monitoring/prometheus/rules.yml:/etc/prometheus/rules.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend
      - db
    networks:
      - deuquantas

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ../monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ../monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3002:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - deuquantas

  postgres_exporter:
    image: wrouesnel/postgres_exporter
    container_name: postgres_exporter
    environment:
      DATA_SOURCE_URI: "postgresql://postgres:password@db:5432/deuquantas?sslmode=disable"
      DATA_SOURCE_USER: "postgres"
      DATA_SOURCE_PASS: "password"
    ports:
      - "9187:9187"
    depends_on:
      - db
    networks:
      - deuquantas

networks:
  deuquantas:
    driver: bridge

volumes:
  db_data:
