version: "3.8"

services:
  backend:
    build:
      context: ../../backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/deuquantas"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deuquantas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend-web:
    build:
      context: ../../frontend-web
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      REACT_APP_BACKEND_URL: "http://localhost:8000"

  frontend-mobile:
    build:
      context: ../../frontend-mobile
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      API_URL: "http://localhost:8000"

volumes:
  db_data:
