services:
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/backend/Dockerfile
    container_name: deuquantas-backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgres://postgres:1029@deuquantas-db:5432/deuquantas"
      JWT_SECRET: "chave-super-secreta"
      NODE_ENV: "development"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    container_name: deuquantas-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1029
      POSTGRES_DB: deuquantas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend-web:
    build:
      context: ../../
      dockerfile: infra/docker/frontend/web/Dockerfile.dev
    container_name: deuquantas-frontend-web
    restart: always
    ports:
      - "3001:3000"  # Alterado para evitar conflito com backend na porta 3000
    depends_on:
      - backend
    environment:
      PORT: 3000
      NEXT_PUBLIC_DOCKER_ENV: true
      REACT_APP_BACKEND_URL: "http://backend:3000"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../../frontend-web:/app
      - /app/node_modules

  # frontend-mobile:
  #   build:
  #     context: ../../
  #     dockerfile: infra/docker/frontend/mobile/Dockerfile
  #   container_name: deuquantas-frontend-mobile
  #   restart: always
  #   ports:
  #     - "4000:80"
  #   depends_on:
  #     - backend
  #   environment:
  #     API_URL: "http://backend:3000"

volumes:
  db_data:
