services:
  backend:
    build:
      context: ../../backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: "postgres://user:password@db:5432/deuquantas"
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: deuquantas
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend-web:
    build:
      context: ../../frontend-web
      #dockerfile: ${DOCKERFILE:-Dockerfile.dev} # Uncomment this line if you want to use the .env file
      dockerfile: Dockerfile.dev
    ports:
    # - "${EXPOSE_PORT}:${EXPOSE_PORT}" # Uncomment this line if you want to expose the port using the .env file
      - "3000:3000"
    depends_on:
      - backend
    environment:
      PORT: 3000
      NEXT_PUBLIC_DOCKER_ENV: true
      REACT_APP_BACKEND_URL: "http://localhost:8000"
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - ../../frontend-web:/app
      - /app/node_modules

  frontend-mobile:
    build:
      context: ../../frontend-mobile
    ports:
      - "4000:80"
    depends_on:
      - backend
    environment:
      API_URL: "http://localhost:8000"

volumes:
  db_data:
