FROM node:20-alpine

WORKDIR /app

COPY ../../frontend-web/package*.json ./

# Define permissão para evitar problemas com usuários diferentes
RUN npm install --force 

COPY . .

RUN npx next --version

EXPOSE 3000

CMD ["npm", "run", "dev"]
