FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

# Define permissão para evitar problemas com usuários diferentes
RUN npm install --force && chmod -R 777 /app/node_modules

COPY . .

RUN npx next --version

EXPOSE 3000

CMD ["npm", "run", "dev"]
