---
- name: Configurar Backend
  hosts: backend
  become: true

  tasks:
    - name: Atualizar pacotes
      apt:
        update_cache: yes

    - name: Instalar dependências do sistema
      apt:
        name:
          - python3
          - python3-pip
          - libpq-dev
        state: present

    - name: Instalar dependências do Python
      pip:
        name:
          - flask
          - psycopg2-binary
          - gunicorn
        executable: pip3

    - name: Criar diretório da aplicação
      file:
        path: /var/www/backend
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: Copiar arquivos do backend
      copy:
        src: ../deuquantas-backend/
        dest: /var/www/backend/
        owner: ubuntu
        group: ubuntu

    - name: Configurar Gunicorn
      template:
        src: gunicorn.service.j2
        dest: /etc/systemd/system/gunicorn.service

    - name: Reiniciar Gunicorn
      shell: systemctl restart gunicorn
