---
- name: Configurar Backend Localmente
  hosts: local
  become: true

  tasks:
    - name: Atualizar pacotes do sistema
      apt:
        update_cache: yes

    - name: Instalar dependências do sistema
      apt:
        name:
          - docker.io
          - docker-compose
        state: present

    - name: Garantir que o Docker está rodando
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Criar diretório da aplicação
      file:
        path: /var/www/deuquantas-backend
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_id }}"

    - name: Baixar e rodar o Backend com Docker
      shell: |
        docker pull majorssolutions/deuquantas-backend:latest
        docker stop deuquantas-backend || true
        docker rm deuquantas-backend || true
        docker run -d --name deuquantas-backend -p 3000:3000 \
          -e DATABASE_URL="postgres://user:password@db:5432/deuquantas" \
          -e JWT_SECRET="chave-super-secreta" \
          majorssolutions/deuquantas-backend:latest

    - name: Abrir firewall para o backend (se necessário)
      ufw:
        rule: allow
        port: "3000"
        proto: tcp
