---
- name: Configurar PostgreSQL
  hosts: database_servers
  become: yes
  vars:
    postgres_version: "15"
    db_name: "deuquantas_db"
    db_user: "deuquantas_user"
    db_password: "secure_password"
  tasks:

    - name: Instalar PostgreSQL
      apt:
        name: "postgresql-{{ postgres_version }}"
        state: present
      when: ansible_os_family == "Debian"

    - name: Garantir que o serviço PostgreSQL está rodando
      service:
        name: postgresql
        state: started
        enabled: yes

    # - name: Criar usuário no PostgreSQL
    #   become: yes
    #   become_method: sudo
    #   become_user: postgres
    #   postgresql_user:
    #     name: "{{ db_user }}"
    #     password: "{{ db_password }}"
    #     role_attr_flags: CREATEDB
    #     port: 5432

    # - name: Criar banco de dados
    #   become_user: postgres
    #   postgresql_db:
    #     name: "{{ db_name }}"
    #     owner: "{{ db_user }}"

    - name: Configurar permissões no banco de dados
      become_user: postgres
      postgresql_privs:
        db: "{{ db_name }}"
        role: "{{ db_user }}"
        privs: "ALL"

    - name: Ajustar configurações de otimização
      lineinfile:
        path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
        line: "max_connections = 200"
      notify: Restart PostgreSQL

  handlers:
    - name: Restart PostgreSQL
      service:
        name: postgresql
        state: restarted
